name: Build and deploy to dev

on: 
  push:
    branches: 
      - dev

env:
  APP_SERVICE_NAME: wap-cx-user-360-dev
  ACR_HOST        : cxuser360registry.azurecr.io
  DOCKER_IMAGE    : cx-user-360-webapp
  DOCKER_TAG      : "1.0.3"
  
jobs:
  build-and-deploy-dev:
    environment: dev
    runs-on    : ubuntu-latest
    
    steps:
    - name: Checkout GitHub Actions
      uses: actions/checkout@v2
      with: 
        ref : 'dev'
     
    - name: Build and push container image to registry
      id  : container-registry
      uses: mr-smithers-excellent/docker-build-push@v5.5
      with: 
        dockerfile : dockerfile.ci
        image      : ${{ env.DOCKER_IMAGE }}
        tags       : ${{ env.DOCKER_TAG }}
        registry   : ${{ env.ACR_HOST }}
        username   : ${{ secrets.REGISTRY_USERNAME }}
        password   : ${{ secrets.REGISTRY_PASSWORD }}
        
    - name: Deploy to App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name   : ${{ env.APP_SERVICE_NAME }}
        images     : ${{ env.ACR_HOST }}/${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
        publish-profile : ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        
